name: explore-eqa
channels:
  - hcc
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - attrs=23.2.0=pyh71513ae_0
  - blas=1.0=mkl
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.0.9=py39h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.2.2=hbcca054_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py39h5eee18b_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cmake=3.14.0=h52cb24c_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.0=py39h7633fee_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.3.2=hca11adc_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.49.0=py39hd1e30aa_0
  - freetype=2.10.4=h0708190_1
  - future=0.18.3=py39h06a4308_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.42=pyhd8ed1ab_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=h59595ed_0
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.13=h85f3911_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - imageio=2.34.0=pyh4b66e23_0
  - imageio-ffmpeg=0.4.9=pyhd8ed1ab_0
  - importlib_resources=6.1.2=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.5=py39h7633fee_1
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.5.0=h251f7ec_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.78.4=hdc74915_0
  - libgomp=13.2.0=h807b86a_5
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=12_linux64_mkl
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=3.16.0=h780b84a_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.3.0=hf544144_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.10.4=hf1b16e4_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.42.0=py39h6a678d5_0
  - lz4-c=1.9.4=hcb278e6_0
  - magma=2.5.4=hc72dce7_4
  - markupsafe=2.1.3=py39h5eee18b_0
  - matplotlib=3.8.0=py39hf3d152e_2
  - matplotlib-base=3.8.0=py39h1128e8f_0
  - mkl=2021.4.0=h06a4308_640
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.1.0=h5cefa2a_0
  - mpmath=1.3.0=py39h06a4308_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=5.7.20=hf484d3e_1001
  - nccl=2.20.5.1=h0800d71_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - ninja-base=1.10.2=hd09550d_5
  - numba=0.59.0=py39h615d6bd_1
  - olefile=0.47=pyhd8ed1ab_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.2.1=hd590300_1
  - packaging=23.2=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_0
  - pillow=10.2.0=py39h5eee18b_0
  - pip=23.3.1=py39h06a4308_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.21=pyhd3eb1b0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.4=py39h5a03fae_0
  - pyqt5-sip=12.9.0=py39h5a03fae_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pyyaml=6.0.1=py39h5eee18b_0
  - qt-main=5.15.2=h53bd1ea_10
  - quaternion=2023.0.2=py39h44dd56e_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py39h06a4308_1
  - rhash=1.4.3=hdbd6064_0
  - scipy=1.12.0=py39h474f0d3_2
  - sip=6.5.1=py39he80948d_2
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - smmap=3.0.5=pyh44b312d_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py39h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.4=py39hd1e30aa_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py39hd1e30aa_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wheel=0.41.2=py39h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxcursor=1.2.0=h0b41bf4_1
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxinerama=1.1.5=h27087fc_0
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-randrproto=1.5.0=h7f98852_1001
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - accelerate==0.27.2
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - chardet==5.2.0
      - click==8.1.7
      - docker-pycreds==0.4.0
      - draccus==0.7.1
      - einops==0.7.0
      - filelock==3.9.0
      - fsspec==2024.2.0
      - ftfy==6.1.3
      - huggingface-hub==0.17.3
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonlines==4.0.0
      - lazy-loader==0.3
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - pathspec==0.12.1
      - protobuf==4.25.3
      - pyyaml-include==1.3.2
      - regex==2023.12.25
      - rich==13.7.1
      - safetensors==0.4.2
      - scikit-image==0.22.0
      - scikit-learn==1.4.1.post1
      - sentry-sdk==1.40.6
      - setproctitle==1.3.3
      - setuptools==69.2.0
      - threadpoolctl==3.3.0
      - tifffile==2024.2.12
      - timm==0.9.16
      - tokenizers==0.14.1
      - tomli==2.0.1
      - torch==2.2.1
      - torchaudio==2.2.1
      - torchvision==0.17.1
      - transformers==4.34.1
      - triton==2.2.0
      - typing-inspect==0.9.0
      - wandb==0.16.3